.TH "CommonUtils/AdvancedIteration.h" 3 "Sat May 29 2021" "Version 1.1" "CommonLibs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommonUtils/AdvancedIteration.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Private/AdvancedIteration\&.tpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBCommon\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename IteratorType > size_t \fBCommon::GetIteratorDistance\fP (IteratorType Begin, IteratorType End)"
.br
.RI "Counts elements between two iterators\&. Range: [Begin: End) "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CommonLibs from the source code\&.
