.TH "CommonTypes/Iterators/Block.h" 3 "Sat May 29 2021" "Version 1.1" "CommonLibs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommonTypes/Iterators/Block.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./Private/Iterators/Block\&.tpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCommon::Iterators::TBlockIterator< PtrType, RefType >\fP"
.br
.ti -1c
.RI "class \fBCommon::Iterators::TReverseBlockIterator< PtrType, RefType >\fP"
.br
.ti -1c
.RI "class \fBCommon::Iterators::TSafeBlockIterator< PtrType, RefType, ContType >\fP"
.br
.ti -1c
.RI "class \fBCommon::Iterators::TSafeReverseBlockIterator< PtrType, RefType, ContType >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBCommon\fP"
.br
.ti -1c
.RI " \fBCommon::Iterators\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CommonLibs from the source code\&.
