.TH "Common::Iterators::TSafeReverseBlockIterator< PtrType, RefType, ContType >" 3 "Tue Jun 1 2021" "Version 1.1" "CommonLibs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Common::Iterators::TSafeReverseBlockIterator< PtrType, RefType, ContType >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'CommonTypes/Iterators/Block\&.h'\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTSafeReverseBlockIterator\fP (PtrType InitialPosition, const ContType Owner)"
.br
.ti -1c
.RI "const \fBTSafeReverseBlockIterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBTSafeReverseBlockIterator\fP \fBoperator+\fP (size_t Offset)"
.br
.ti -1c
.RI "const \fBTSafeReverseBlockIterator\fP & \fBoperator+=\fP (size_t Offset)"
.br
.ti -1c
.RI "const \fBTSafeReverseBlockIterator\fP & \fBoperator\-\-\fP ()"
.br
.ti -1c
.RI "\fBTSafeReverseBlockIterator\fP \fBoperator\-\fP (size_t Offset)"
.br
.ti -1c
.RI "const \fBTSafeReverseBlockIterator\fP & \fBoperator\-=\fP (size_t Offset)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBTSafeReverseBlockIterator\fP &Other)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBTSafeReverseBlockIterator\fP &Other)"
.br
.ti -1c
.RI "RefType \fBoperator*\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename PtrType , typename RefType , class ContType > \fBCommon::Iterators::TSafeReverseBlockIterator\fP< PtrType, RefType, ContType >::\fBTSafeReverseBlockIterator\fP (PtrType InitialPosition, const ContType Owner)"

.SH "Member Function Documentation"
.PP 
.SS "template<typename PtrType , typename RefType , class ContType > const \fBTSafeReverseBlockIterator\fP& \fBCommon::Iterators::TSafeReverseBlockIterator\fP< PtrType, RefType, ContType >::operator++ ()"

.SS "template<typename PtrType , typename RefType , class ContType > \fBTSafeReverseBlockIterator\fP \fBCommon::Iterators::TSafeReverseBlockIterator\fP< PtrType, RefType, ContType >::operator+ (size_t Offset)"

.SS "template<typename PtrType , typename RefType , class ContType > const \fBTSafeReverseBlockIterator\fP& \fBCommon::Iterators::TSafeReverseBlockIterator\fP< PtrType, RefType, ContType >::operator+= (size_t Offset)"

.SS "template<typename PtrType , typename RefType , class ContType > const \fBTSafeReverseBlockIterator\fP& \fBCommon::Iterators::TSafeReverseBlockIterator\fP< PtrType, RefType, ContType >::operator\-\- ()"

.SS "template<typename PtrType , typename RefType , class ContType > \fBTSafeReverseBlockIterator\fP \fBCommon::Iterators::TSafeReverseBlockIterator\fP< PtrType, RefType, ContType >::operator\- (size_t Offset)"

.SS "template<typename PtrType , typename RefType , class ContType > const \fBTSafeReverseBlockIterator\fP& \fBCommon::Iterators::TSafeReverseBlockIterator\fP< PtrType, RefType, ContType >::operator\-= (size_t Offset)"

.SS "template<typename PtrType , typename RefType , class ContType > bool \fBCommon::Iterators::TSafeReverseBlockIterator\fP< PtrType, RefType, ContType >::operator== (const \fBTSafeReverseBlockIterator\fP< PtrType, RefType, ContType > & Other)"

.SS "template<typename PtrType , typename RefType , class ContType > bool \fBCommon::Iterators::TSafeReverseBlockIterator\fP< PtrType, RefType, ContType >::operator!= (const \fBTSafeReverseBlockIterator\fP< PtrType, RefType, ContType > & Other)"

.SS "template<typename PtrType , typename RefType , class ContType > RefType \fBCommon::Iterators::TSafeReverseBlockIterator\fP< PtrType, RefType, ContType >::operator* ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for CommonLibs from the source code\&.
