.TH "Common::Iterators::TReverseBlockIterator< PtrType, RefType >" 3 "Tue Jun 1 2021" "Version 1.1" "CommonLibs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Common::Iterators::TReverseBlockIterator< PtrType, RefType >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'CommonTypes/Iterators/Block\&.h'\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTReverseBlockIterator\fP ()"
.br
.ti -1c
.RI "\fBTReverseBlockIterator\fP (PtrType InitialPosition)"
.br
.ti -1c
.RI "const \fBTReverseBlockIterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBTReverseBlockIterator\fP \fBoperator+\fP (size_t Offset)"
.br
.ti -1c
.RI "const \fBTReverseBlockIterator\fP & \fBoperator+=\fP (size_t Offset)"
.br
.ti -1c
.RI "const \fBTReverseBlockIterator\fP & \fBoperator\-\-\fP ()"
.br
.ti -1c
.RI "\fBTReverseBlockIterator\fP \fBoperator\-\fP (size_t Offset)"
.br
.ti -1c
.RI "const \fBTReverseBlockIterator\fP & \fBoperator\-=\fP (size_t Offset)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBTReverseBlockIterator\fP &Other)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBTReverseBlockIterator\fP &Other)"
.br
.ti -1c
.RI "RefType \fBoperator*\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename PtrType , typename RefType > \fBCommon::Iterators::TReverseBlockIterator\fP< PtrType, RefType >::\fBTReverseBlockIterator\fP ()"

.SS "template<typename PtrType , typename RefType > \fBCommon::Iterators::TReverseBlockIterator\fP< PtrType, RefType >::\fBTReverseBlockIterator\fP (PtrType InitialPosition)"

.SH "Member Function Documentation"
.PP 
.SS "template<typename PtrType , typename RefType > const \fBTReverseBlockIterator\fP& \fBCommon::Iterators::TReverseBlockIterator\fP< PtrType, RefType >::operator++ ()"

.SS "template<typename PtrType , typename RefType > \fBTReverseBlockIterator\fP \fBCommon::Iterators::TReverseBlockIterator\fP< PtrType, RefType >::operator+ (size_t Offset)"

.SS "template<typename PtrType , typename RefType > const \fBTReverseBlockIterator\fP& \fBCommon::Iterators::TReverseBlockIterator\fP< PtrType, RefType >::operator+= (size_t Offset)"

.SS "template<typename PtrType , typename RefType > const \fBTReverseBlockIterator\fP& \fBCommon::Iterators::TReverseBlockIterator\fP< PtrType, RefType >::operator\-\- ()"

.SS "template<typename PtrType , typename RefType > \fBTReverseBlockIterator\fP \fBCommon::Iterators::TReverseBlockIterator\fP< PtrType, RefType >::operator\- (size_t Offset)"

.SS "template<typename PtrType , typename RefType > const \fBTReverseBlockIterator\fP& \fBCommon::Iterators::TReverseBlockIterator\fP< PtrType, RefType >::operator\-= (size_t Offset)"

.SS "template<typename PtrType , typename RefType > bool \fBCommon::Iterators::TReverseBlockIterator\fP< PtrType, RefType >::operator== (const \fBTReverseBlockIterator\fP< PtrType, RefType > & Other)"

.SS "template<typename PtrType , typename RefType > bool \fBCommon::Iterators::TReverseBlockIterator\fP< PtrType, RefType >::operator!= (const \fBTReverseBlockIterator\fP< PtrType, RefType > & Other)"

.SS "template<typename PtrType , typename RefType > RefType \fBCommon::Iterators::TReverseBlockIterator\fP< PtrType, RefType >::operator* ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for CommonLibs from the source code\&.
