.TH "Common::Iterators::TSafeBlockIterator< PtrType, RefType, ContType >" 3 "Sat May 29 2021" "Version 1.1" "CommonLibs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Common::Iterators::TSafeBlockIterator< PtrType, RefType, ContType >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'CommonTypes/Iterators/Block\&.h'\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTSafeBlockIterator\fP (PtrType InitialPosition, const ContType Owner)"
.br
.ti -1c
.RI "const \fBTSafeBlockIterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBTSafeBlockIterator\fP \fBoperator+\fP (size_t Offset)"
.br
.ti -1c
.RI "const \fBTSafeBlockIterator\fP & \fBoperator+=\fP (size_t Offset)"
.br
.ti -1c
.RI "const \fBTSafeBlockIterator\fP & \fBoperator\-\-\fP ()"
.br
.ti -1c
.RI "\fBTSafeBlockIterator\fP \fBoperator\-\fP (size_t Offset)"
.br
.ti -1c
.RI "const \fBTSafeBlockIterator\fP & \fBoperator\-=\fP (size_t Offset)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBTSafeBlockIterator\fP &Other)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBTSafeBlockIterator\fP &Other)"
.br
.ti -1c
.RI "RefType \fBoperator*\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename PtrType , typename RefType , typename ContType > \fBCommon::Iterators::TSafeBlockIterator\fP< PtrType, RefType, ContType >::\fBTSafeBlockIterator\fP (PtrType InitialPosition, const ContType Owner)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename PtrType , typename RefType , typename ContType > const \fBTSafeBlockIterator\fP& \fBCommon::Iterators::TSafeBlockIterator\fP< PtrType, RefType, ContType >::operator++ ()"

.SS "template<typename PtrType , typename RefType , typename ContType > \fBTSafeBlockIterator\fP \fBCommon::Iterators::TSafeBlockIterator\fP< PtrType, RefType, ContType >::operator+ (size_t Offset)"

.SS "template<typename PtrType , typename RefType , typename ContType > const \fBTSafeBlockIterator\fP& \fBCommon::Iterators::TSafeBlockIterator\fP< PtrType, RefType, ContType >::operator+= (size_t Offset)"

.SS "template<typename PtrType , typename RefType , typename ContType > const \fBTSafeBlockIterator\fP& \fBCommon::Iterators::TSafeBlockIterator\fP< PtrType, RefType, ContType >::operator\-\- ()"

.SS "template<typename PtrType , typename RefType , typename ContType > \fBTSafeBlockIterator\fP \fBCommon::Iterators::TSafeBlockIterator\fP< PtrType, RefType, ContType >::operator\- (size_t Offset)"

.SS "template<typename PtrType , typename RefType , typename ContType > const \fBTSafeBlockIterator\fP& \fBCommon::Iterators::TSafeBlockIterator\fP< PtrType, RefType, ContType >::operator\-= (size_t Offset)"

.SS "template<typename PtrType , typename RefType , typename ContType > bool \fBCommon::Iterators::TSafeBlockIterator\fP< PtrType, RefType, ContType >::operator== (const \fBTSafeBlockIterator\fP< PtrType, RefType, ContType > & Other)"

.SS "template<typename PtrType , typename RefType , typename ContType > bool \fBCommon::Iterators::TSafeBlockIterator\fP< PtrType, RefType, ContType >::operator!= (const \fBTSafeBlockIterator\fP< PtrType, RefType, ContType > & Other)"

.SS "template<typename PtrType , typename RefType , typename ContType > RefType \fBCommon::Iterators::TSafeBlockIterator\fP< PtrType, RefType, ContType >::operator* ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for CommonLibs from the source code\&.
