.TH "Common::TList< T >::Node" 3 "Tue Jun 1 2021" "Version 1.1" "CommonLibs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Common::TList< T >::Node
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'CommonTypes/List\&.h'\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP (T Value, \fBNode\fP *\fBPrevious\fP=nullptr, \fBNode\fP *\fBNext\fP=nullptr)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBBuffer\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBNext\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBPrevious\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBCommon::TList\fP< T >::Node::Node (T Value, \fBNode\fP * Previous = \fCnullptr\fP, \fBNode\fP * Next = \fCnullptr\fP)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename T > T \fBCommon::TList\fP< T >::Node::Buffer"

.SS "template<typename T > \fBNode\fP* \fBCommon::TList\fP< T >::Node::Next"

.SS "template<typename T > \fBNode\fP* \fBCommon::TList\fP< T >::Node::Previous"


.SH "Author"
.PP 
Generated automatically by Doxygen for CommonLibs from the source code\&.
