.TH "Common::Iterators::TSafeReverseDoublyLinkedIterator< NdPtrType, ValRefType >" 3 "Tue Jun 1 2021" "Version 1.1" "CommonLibs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Common::Iterators::TSafeReverseDoublyLinkedIterator< NdPtrType, ValRefType >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'CommonTypes/Iterators/DoublyLinked\&.h'\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTSafeReverseDoublyLinkedIterator\fP ()"
.br
.ti -1c
.RI "\fBTSafeReverseDoublyLinkedIterator\fP (NdPtrType InitialPosition)"
.br
.ti -1c
.RI "const \fBTSafeReverseDoublyLinkedIterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBTSafeReverseDoublyLinkedIterator\fP \fBoperator+\fP (size_t Offset)"
.br
.ti -1c
.RI "const \fBTSafeReverseDoublyLinkedIterator\fP & \fBoperator+=\fP (size_t Offset)"
.br
.ti -1c
.RI "const \fBTSafeReverseDoublyLinkedIterator\fP & \fBoperator\-\-\fP ()"
.br
.ti -1c
.RI "\fBTSafeReverseDoublyLinkedIterator\fP \fBoperator\-\fP (size_t Offset)"
.br
.ti -1c
.RI "const \fBTSafeReverseDoublyLinkedIterator\fP & \fBoperator\-=\fP (size_t Offset)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBTSafeReverseDoublyLinkedIterator\fP &Other)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBTSafeReverseDoublyLinkedIterator\fP &Other)"
.br
.ti -1c
.RI "ValRefType \fBoperator*\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "NdPtrType \fBNodePointer\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class NdPtrType , typename ValRefType > \fBCommon::Iterators::TSafeReverseDoublyLinkedIterator\fP< NdPtrType, ValRefType >::\fBTSafeReverseDoublyLinkedIterator\fP ()"

.SS "template<class NdPtrType , typename ValRefType > \fBCommon::Iterators::TSafeReverseDoublyLinkedIterator\fP< NdPtrType, ValRefType >::\fBTSafeReverseDoublyLinkedIterator\fP (NdPtrType InitialPosition)"

.SH "Member Function Documentation"
.PP 
.SS "template<class NdPtrType , typename ValRefType > const \fBTSafeReverseDoublyLinkedIterator\fP& \fBCommon::Iterators::TSafeReverseDoublyLinkedIterator\fP< NdPtrType, ValRefType >::operator++ ()"

.SS "template<class NdPtrType , typename ValRefType > \fBTSafeReverseDoublyLinkedIterator\fP \fBCommon::Iterators::TSafeReverseDoublyLinkedIterator\fP< NdPtrType, ValRefType >::operator+ (size_t Offset)"

.SS "template<class NdPtrType , typename ValRefType > const \fBTSafeReverseDoublyLinkedIterator\fP& \fBCommon::Iterators::TSafeReverseDoublyLinkedIterator\fP< NdPtrType, ValRefType >::operator+= (size_t Offset)"

.SS "template<class NdPtrType , typename ValRefType > const \fBTSafeReverseDoublyLinkedIterator\fP& \fBCommon::Iterators::TSafeReverseDoublyLinkedIterator\fP< NdPtrType, ValRefType >::operator\-\- ()"

.SS "template<class NdPtrType , typename ValRefType > \fBTSafeReverseDoublyLinkedIterator\fP \fBCommon::Iterators::TSafeReverseDoublyLinkedIterator\fP< NdPtrType, ValRefType >::operator\- (size_t Offset)"

.SS "template<class NdPtrType , typename ValRefType > const \fBTSafeReverseDoublyLinkedIterator\fP& \fBCommon::Iterators::TSafeReverseDoublyLinkedIterator\fP< NdPtrType, ValRefType >::operator\-= (size_t Offset)"

.SS "template<class NdPtrType , typename ValRefType > bool \fBCommon::Iterators::TSafeReverseDoublyLinkedIterator\fP< NdPtrType, ValRefType >::operator== (const \fBTSafeReverseDoublyLinkedIterator\fP< NdPtrType, ValRefType > & Other)"

.SS "template<class NdPtrType , typename ValRefType > bool \fBCommon::Iterators::TSafeReverseDoublyLinkedIterator\fP< NdPtrType, ValRefType >::operator!= (const \fBTSafeReverseDoublyLinkedIterator\fP< NdPtrType, ValRefType > & Other)"

.SS "template<class NdPtrType , typename ValRefType > ValRefType \fBCommon::Iterators::TSafeReverseDoublyLinkedIterator\fP< NdPtrType, ValRefType >::operator* ()"

.SH "Member Data Documentation"
.PP 
.SS "template<class NdPtrType , typename ValRefType > NdPtrType \fBCommon::Iterators::TSafeReverseDoublyLinkedIterator\fP< NdPtrType, ValRefType >::NodePointer"


.SH "Author"
.PP 
Generated automatically by Doxygen for CommonLibs from the source code\&.
