.TH "Common::RemoveReference< T >" 3 "Tue Jun 1 2021" "Version 1.1" "CommonLibs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Common::RemoveReference< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'CommonUtils/TypeOperations\&.h'\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T \fBType\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T > typedef T \fBCommon::RemoveReference\fP< T >::\fBType\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CommonLibs from the source code\&.
