.TH "CommonTypes/List.h" 3 "Tue Jun 1 2021" "Version 1.1" "CommonLibs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommonTypes/List.h
.SH SYNOPSIS
.br
.PP
\fC#include <initializer_list>\fP
.br
\fC#include 'Iterators/DoublyLinked\&.h'\fP
.br
\fC#include '\&./\&.\&./CommonUtils/TypeOperations\&.h'\fP
.br
\fC#include 'Private/List/List\&.tpp'\fP
.br
\fC#include 'Private/List/Iterator\&.tpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCommon::TList< T >\fP"
.br
.RI "Container representing Doubly linked list\&. "
.ti -1c
.RI "class \fBCommon::TList< T >::Node\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBCommon\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CommonLibs from the source code\&.
