.TH "CommonTypes/Optional.h" 3 "Tue Jun 1 2021" "Version 1.1" "CommonLibs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommonTypes/Optional.h
.SH SYNOPSIS
.br
.PP
\fC#include <new>\fP
.br
\fC#include 'Exception\&.h'\fP
.br
\fC#include '\&./\&.\&./CommonUtils/TypeOperations\&.h'\fP
.br
\fC#include 'Private/Optional\&.tpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCommon::TOptional< T >\fP"
.br
.RI "Represents object that may not exist\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBCommon\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CommonLibs from the source code\&.
