.TH "CommonTypes/Pair.h" 3 "Tue Jun 1 2021" "Version 1.1" "CommonLibs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommonTypes/Pair.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCommon::TPair< T1, T2 >\fP"
.br
.RI "Container that represents a pair of objects\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBCommon\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T1 , typename T2 > TPair< T1, T2 > \fBCommon::MakePair\fP (const T1 &First, const T2 &Second) noexcept"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CommonLibs from the source code\&.
