.TH "CommonUtils/Sort.h" 3 "Tue Jun 1 2021" "Version 1.1" "CommonLibs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommonUtils/Sort.h
.SH SYNOPSIS
.br
.PP
\fC#include 'TypeOperations\&.h'\fP
.br
\fC#include 'AdvancedIteration\&.h'\fP
.br
\fC#include 'Private/Sort\&.tpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBCommon\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename IteratorType , typename FunctionType > void \fBCommon::BubbleSort\fP (IteratorType Begin, IteratorType End, FunctionType Comparator)"
.br
.ti -1c
.RI "template<typename IteratorType , typename FunctionType > void \fBCommon::SelectionSort\fP (IteratorType Begin, IteratorType End, FunctionType Comparator)"
.br
.ti -1c
.RI "template<typename IteratorType , typename FunctionType > void \fBCommon::QuickSort\fP (IteratorType Begin, IteratorType End, FunctionType Comparator)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CommonLibs from the source code\&.
