.TH "CommonTypes/Vector.h" 3 "Tue Jun 1 2021" "Version 1.1" "CommonLibs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommonTypes/Vector.h
.SH SYNOPSIS
.br
.PP
\fC#include <initializer_list>\fP
.br
\fC#include <type_traits>\fP
.br
\fC#include 'Exception\&.h'\fP
.br
\fC#include 'Iterators/Block\&.h'\fP
.br
\fC#include '\&.\&./CommonUtils/Assert\&.h'\fP
.br
\fC#include '\&./\&.\&./CommonUtils/TypeOperations\&.h'\fP
.br
\fC#include '\&./\&.\&./CommonUtils/AdvancedIteration\&.h'\fP
.br
\fC#include '\&./\&.\&./CommonUtils/BlockAllocation\&.h'\fP
.br
\fC#include 'Private/Vector/Vector\&.tpp'\fP
.br
\fC#include 'Private/Vector/Iterator\&.tpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCommon::TVector< T >\fP"
.br
.RI "Container representing array that can change its size\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBCommon\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CommonLibs from the source code\&.
